### PR TITLE
Bharat| Support for groovy based Data Integrity rules.

### PR DESCRIPTION
**Pull request by bharatak**
Will support groovy based data integrity rules.  The README is updated with the instructions.

### CODE REVIEW

**Comment by bharatak** [comment]
@ssmusoke This PR is for supporting groovy based Data Integrity rules.  This helps in writing groovy files without the need for creating a custom omod for writing the rules.  Can I request you to validate and merge this PR?  Thank you.

**Comment by dkayiwa** [comment]
@ssmusoke how about giving @bharatak direct commit access to this repo? :)

**Comment by bharatak** [comment]
I have the access .. but want to keep @ssmusoke in loop :)

**Comment by dkayiwa** [comment]
Oh i see! I like that! 👍

**Pull request merged**
