### PR TITLE
DINT-68-1: Refactored classes and packages to match the layout of other modules

### PR DESCRIPTION
**Pull request by ssmusoke**
First pull request of the series for the DINT-68 issue 

- Removed dataintegrity- prefix from api and omod projects
- Moved hbm and resource files to api from omod
- Moved model files from api to omod

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you notice the travis failure?

**Comment by ssmusoke** [comment]
@dkayiwa yes looking into it, was not evident on my local machine

**Comment by ssmusoke** [comment]
@dkayiwa Thanks will look into it. One question though - where do I put information to ensure that the dataintegrity.database_version property is updated. I see the version has not changed across the versions as this module was refactored

**Comment by ssmusoke** [comment]
Created a ticket for this https://issues.openmrs.org/browse/DINT-75

**Comment by dkayiwa** [comment]
@ssmusoke that property is not relevant for modules which are using liquibase.xml instead of sqldiff.xml
So that explains the behaviour you see.

**Comment by ssmusoke** [comment]
@dkayiwa Okay. So another question How do I add a changeset that has to be run before others, do I put it at the bottom or top of the liquibase.xml file?

**Comment by dkayiwa** [comment]
At the top. They are executed in the order they appear in the file.

**Comment by ssmusoke** [comment]
@dkayiwa The ones at the top are executed before the ones at the bottom?

**Comment by dkayiwa** [comment]
Correct.

**Pull request merged**
